name: Test Build Deploy 

on:
  pull_request:
    types:
      - opened 

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run: echo "Hello from init"

      - name: Get code 
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Deploy project 
        run: echo "Deploying ..."
