name: Test Project

on: push 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run: echo "Hello from init"

      - name: Get code 
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
